// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"


import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ExchangeSubscriptionController from "./exchange_subscription_controller"
application.register("exchange-subscription", ExchangeSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import OngletController from "./onglet_controller"
application.register("onglet", OngletController)

import UserVinylController from "./user_vinyl_controller"
application.register("user-vinyl", UserVinylController)
